String.toLocaleString({

  "it": {
    "%game-intro": "Join the <strong>Cupcakes!</strong>",
    "%restart-button": "Play Again",
    "%keep-playing-button": "Keep going",
    "%retry-button": "Retry",
    "%game-won": "You win!",
    "%game-over": "Game over!",
    "%game-explanation": "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer": "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits": "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1": "I scored \"",
    "%tweet2": " at 2048-CUPCAKES #2048game",
    "%tile-legend": "<strong class=\"important\">Tile Legend:</strong>",
    '%2': 'vanilla birthday',
    '%4': 'bubblegum pink',
    '%8': 'sunshine vanilla',
    '%16': 'valrhona blonde ganache',
    '%32': 'chocolare peanut butter cheesecake',
    '%64': 'chocolate mint fudge',
    '%128': 'chocolate spider web',
    '%256': 'toasted marshmallow',
    '%512': 'cookies and creme',
    '%1024': 'chocolate sundae',
    '%2048': 'white chocolate peppermint',
    '%4096': '2017 Confetti Vanilla',
    '%8192': 'Rainbow',
    '%p0': 'vanilla birthday',
    '%p4': 'bubblegum pink',
    '%p8': 'sunshine vanilla',
    '%p16': 'valrhona blonde ganache',
    '%p32': 'choc. peanut butter cheesecake',
    '%p64': 'choc. mint fudge',
    '%p128': 'choc. spider web',
    '%p256': 'toasted marshmallow',
    '%p512': 'cookies and creme',
    '%p1024': 'choc. sundae',
    '%p2048': 'white choc. peppermint',
    '%p4096': '2017 Confetti Vanilla',
    '%p8192': 'Rainbow'

  },

  "zh": {
    "%game-intro": "来玩<strong>纸杯蛋糕</strong>吧！",
    "%restart-button": "重新开始",
    "%keep-playing-button": "继续游戏",
    "%retry-button": "重试",
    "%game-won": "你赢了！",
    "%game-over": "游戏结束！",
    "%game-explanation": "<strong class=\"important\">游戏玩法：</strong>使用<strong>方向键</strong>移动方块。当两个相同的纸杯蛋糕相遇时，它们会<strong>升级！</strong>",
    "%disclaimer": "<strong class=\"important\">注意：</strong>本网站 <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> 是基于 <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a> 创建的 <a href=\"http://git.io/2048\">2048</a> 的衍生版本。",
    "%credits": "纸杯蛋糕图片来自 <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>。",
    "%tweet1": "我在2048-CUPCAKES中得到了",
    "%tweet2": "分 #2048game",
    "%tile-legend": "<strong class=\"important\">蛋糕图例：</strong>",
    "%2": "香草生日蛋糕",
    "%4": "粉色泡泡糖",
    "%8": "阳光香草",
    "%16": "金色香草甘纳许",
    "%32": "巧克力花生酱芝士蛋糕",
    "%64": "巧克力薄荷糖",
    "%128": "巧克力蜘蛛网",
    "%256": "烤棉花糖",
    "%512": "奥利奥奶油",
    "%1024": "巧克力圣代",
    "%2048": "白巧克力薄荷",
    "%4096": "2017彩虹香草",
    "%8192": "彩虹蛋糕",
    "%p0": "香草生日",
    "%p4": "泡泡糖",
    "%p8": "阳光香草",
    "%p16": "金色甘纳许",
    "%p32": "巧克力花生芝士",
    "%p64": "巧薄荷",
    "%p128": "蜘蛛网",
    "%p256": "烤棉花糖",
    "%p512": "奥利奥",
    "%p1024": "巧克力圣代",
    "%p2048": "白巧薄荷",
    "%p4096": "彩虹香草",
    "%p8192": "彩虹"
  },

  "de": {
    "%game-intro": "Verbinde die <strong>Cupcakes!</strong>",
    "%restart-button": "Neu starten",
    "%keep-playing-button": "Weiterspielen",
    "%retry-button": "Wiederholen",
    "%game-won": "Sie haben gewonnen!",
    "%game-over": "Spiel vorbei!",
    "%game-explanation": "<strong class=\"important\">Spielanleitung:</strong> Bewegen Sie die Kacheln mit den <strong>Pfeiltasten</strong>. Wenn zwei Kacheln mit dem gleichen Symbol sich berühren, <strong>werden sie befördert!</strong>",
    "%disclaimer": "<strong class=\"important\">Hinweis:</strong> Diese Seite <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> ist ein Ableger der offiziellen Version von <a href=\"http://git.io/2048\">2048</a>, erstellt von <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits": "Cupcake-Bilder von <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1": "Ich habe ",
    "%tweet2": " bei 2048-CUPCAKES erreicht #2048game",
    "%tile-legend": "<strong class=\"important\">Kachel-Legende:</strong>",
    "%2": "Vanille Geburtstag",
    "%4": "Bubblegum Rosa",
    "%8": "Sonnenschein Vanille",
    "%16": "Valrhona Blonde Ganache",
    "%32": "Schoko-Erdnussbutter-Käsekuchen",
    "%64": "Schoko-Minz-Fudge",
    "%128": "Schokoladen-Spinnennetz",
    "%256": "Geröstete Marshmallow",
    "%512": "Kekse und Sahne",
    "%1024": "Schokoladen-Eisbecher",
    "%2048": "Weiße Schokolade Pfefferminz",
    "%4096": "2017 Konfetti Vanille",
    "%8192": "Regenbogen",
    "%p0": "Vanille",
    "%p4": "Bubblegum",
    "%p8": "Sonnenschein",
    "%p16": "Blonde Ganache",
    "%p32": "Schoko-Erdnuss",
    "%p64": "Schoko-Minz",
    "%p128": "Spinnennetz",
    "%p256": "Marshmallow",
    "%p512": "Kekse & Sahne",
    "%p1024": "Schoko-Eis",
    "%p2048": "Weiße Minz",
    "%p4096": "Konfetti",
    "%p8192": "Regenbogen"
  },

  "en": {
    "%game-intro": "Join the <strong>Cupcakes!</strong>",
    "%restart-button": "Play Again",
    "%keep-playing-button": "Keep going",
    "%retry-button": "Retry",
    "%game-won": "You win!",
    "%game-over": "Game over!",
    "%game-explanation": "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer": "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits": "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1": "I scored \"",
    "%tweet2": " at 2048-CUPCAKES #2048game",
    "%tile-legend": "<strong class=\"important\">Tile Legend:</strong>",
    '%2': 'vanilla birthday',
    '%4': 'bubblegum pink',
    '%8': 'sunshine vanilla',
    '%16': 'valrhona blonde ganache',
    '%32': 'chocolare peanut butter cheesecake',
    '%64': 'chocolate mint fudge',
    '%128': 'chocolate spider web',
    '%256': 'toasted marshmallow',
    '%512': 'cookies and creme',
    '%1024': 'chocolate sundae',
    '%2048': 'white chocolate peppermint',
    '%4096': '2017 Confetti Vanilla',
    '%8192': 'Rainbow',
    '%p0': 'vanilla birthday',
    '%p4': 'bubblegum pink',
    '%p8': 'sunshine vanilla',
    '%p16': 'valrhona blonde ganache',
    '%p32': 'choc. peanut butter cheesecake',
    '%p64': 'choc. mint fudge',
    '%p128': 'choc. spider web',
    '%p256': 'toasted marshmallow',
    '%p512': 'cookies and creme',
    '%p1024': 'choc. sundae',
    '%p2048': 'white choc. peppermint',
    '%p4096': '2017 Confetti Vanilla',
    '%p8192': 'Rainbow'
  },

  "ja": {
    "%game-intro": "<strong>カップケーキ</strong>を始めよう！",
    "%restart-button": "もう一度遊ぶ",
    "%keep-playing-button": "続ける",
    "%retry-button": "再試行",
    "%game-won": "あなたの勝ち！",
    "%game-over": "ゲームオーバー！",
    "%game-explanation": "<strong class=\"important\">遊び方：</strong> <strong>矢印キー</strong>を使ってタイルを動かします。同じシンボルのタイルが接触すると、<strong>昇格します！</strong>",
    "%disclaimer": "<strong class=\"important\">注意：</strong>このサイト <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> は、<a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a> が作成した公式バージョン <a href=\"http://git.io/2048\">2048</a> のスピンオフです。",
    "%credits": "カップケーキの画像は <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a> によるものです。",
    "%tweet1": "私は2048-CUPCAKESで",
    "%tweet2": "点を獲得しました #2048game",
    "%tile-legend": "<strong class=\"important\">タイルの伝説：</strong>",
    "%2": "バニラバースデー",
    "%4": "バブルガムピンク",
    "%8": "サンシャインバニラ",
    "%16": "ヴァローナブロンドガナッシュ",
    "%32": "チョコレートピーナッツバターチーズケーキ",
    "%64": "チョコミントファッジ",
    "%128": "チョコレートスパイダーウェブ",
    "%256": "トーストマシュマロ",
    "%512": "クッキー＆クリーム",
    "%1024": "チョコレートサンデー",
    "%2048": "ホワイトチョコレートペパーミント",
    "%4096": "2017コンフェティバニラ",
    "%8192": "レインボー",
    "%p0": "バニラバースデー",
    "%p4": "バブルガムピンク",
    "%p8": "サンシャインバニラ",
    "%p16": "ヴァローナブロンドガナッシュ",
    "%p32": "チョコレートピーナッツバターチーズケーキ",
    "%p64": "チョコミントファッジ",
    "%p128": "チョコレートスパイダーウェブ",
    "%p256": "トーストマシュマロ",
    "%p512": "クッキー＆クリーム",
    "%p1024": "チョコレートサンデー",
    "%p2048": "ホワイトチョコレートペパーミント",
    "%p4096": "2017コンフェティバニラ",
    "%p8192": "レインボー"
  },
  "fr": {
    "%game-intro": "Rejoignez les <strong>Cupcakes!</strong>",
    "%restart-button": "Rejouer",
    "%keep-playing-button": "Continuer",
    "%retry-button": "Réessayer",
    "%game-won": "Vous avez gagné!",
    "%game-over": "Jeu terminé!",
    "%game-explanation": "<strong class=\"important\">Comment jouer :</strong> Utilisez vos <strong>flèches directionnelles</strong> pour déplacer les tuiles. Lorsque deux tuiles avec le même symbole se touchent, elles <strong>se combinent!</strong>",
    "%disclaimer": "<strong class=\"important\">Remarque :</strong> Ce site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> est un dérivé de la version officielle de <a href=\"http://git.io/2048\">2048</a> créée par <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits": "Images de cupcakes par <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1": "J'ai marqué ",
    "%tweet2": " à 2048-CUPCAKES #2048game",
    "%tile-legend": "<strong class=\"important\">Légende des tuiles :</strong>",
    "%2": "anniversaire vanille",
    "%4": "bubblegum rose",
    "%8": "vanille ensoleillée",
    "%16": "ganache blonde valrhona",
    "%32": "cheesecake au beurre de cacahuète et chocolat",
    "%64": "fudge à la menthe chocolatée",
    "%128": "toile d'araignée en chocolat",
    "%256": "guimauve grillée",
    "%512": "cookies et crème",
    "%1024": "sundae au chocolat",
    "%2048": "menthe au chocolat blanc",
    "%4096": "vanille confetti 2017",
    "%8192": "arc-en-ciel",
    "%p0": "anniversaire vanille",
    "%p4": "bubblegum rose",
    "%p8": "vanille ensoleillée",
    "%p16": "ganache blonde valrhona",
    "%p32": "cheesecake au beurre de cacahuète et chocolat",
    "%p64": "fudge à la menthe chocolatée",
    "%p128": "toile d'araignée en chocolat",
    "%p256": "guimauve grillée",
    "%p512": "cookies et crème",
    "%p1024": "sundae au chocolat",
    "%p2048": "menthe au chocolat blanc",
    "%p4096": "vanille confetti 2017",
    "%p8192": "arc-en-ciel"
  }

});

String.defaultLocale = "en";

